package com;

// default package
// Generated Jul 8, 2016 12:57:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private Integer groupId;
	private String name;
	private Set<Users> users = new HashSet<Users>();

	public Groups() {
	}

	public Groups(String name) {
		this.name = name;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Users> getUsers() {
		return users;
	}

	public void setUsers(Set<Users> users) {
		this.users = users;
	}
	
  public void addUser(Users user) {
        this.users.add(user);
    }

}
